[package]
name = "zachtek"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
ascii = "1.1.0"
clap = { version = "4.4.6", features = ["derive"] }
num_enum = "0.7.0"
serialport = "4.2.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
